GO
CREATE DATABASE DB_5sem
GO
USE DB_5sem;

CREATE TABLE roles
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(50)
)

CREATE TABLE permissions
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(50)
)

CREATE TABLE roles_permissions
(
	id INT PRIMARY KEY IDENTITY,
	role INT NOT NULL FOREIGN KEY REFERENCES roles(id) ON DELETE CASCADE,
	permission INT NOT NULL FOREIGN KEY REFERENCES permissions(id) ON DELETE CASCADE
)

CREATE TABLE accounts
(
	email VARCHAR(255) PRIMARY KEY,
	password VARCHAR(1000) NOT NULL,
	role INT FOREIGN KEY REFERENCES roles(id)
)

CREATE TABLE sponsors
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(128) NOT NULL
)

CREATE TABLE educations
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(128) NOT NULL,
	type CHAR(4) NOT NULL CHECK (type in ('ÂÓÇ', 'ÑÑÓÇ'))
)

CREATE TABLE participants
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(128) NOT NULL,
	phone CHAR(12) NOT NULL,
	education INT NOT NULL FOREIGN KEY REFERENCES educations(id) ON DELETE CASCADE,
	education_time INT NOT NULL CHECK (education_time > 0 AND education_time < 6)
)

CREATE TABLE relationed_accounts
(
	id INT PRIMARY KEY IDENTITY,
	account VARCHAR(255) UNIQUE NOT NULL FOREIGN KEY REFERENCES accounts(email) ON DELETE CASCADE,
	sponsor INT UNIQUE FOREIGN KEY REFERENCES sponsors(id) ON DELETE CASCADE,
	participant INT UNIQUE FOREIGN KEY REFERENCES participants(id) ON DELETE CASCADE
)

CREATE TABLE competitions
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(128) NOT NULL,
	sponsor INT NOT NULL FOREIGN KEY REFERENCES sponsors(id) ON DELETE CASCADE,
)

CREATE TABLE participation
(
	id INT PRIMARY KEY IDENTITY,
	competition INT NOT NULL FOREIGN KEY REFERENCES competitions(id) ON DELETE CASCADE,
	participant INT NOT NULL FOREIGN KEY REFERENCES participants(id) ON DELETE CASCADE,
	start_datetime DATETIME,
	end_datetime DATETIME
)

CREATE TABLE answer_types
(
	id INT PRIMARY KEY IDENTITY,
	name VARCHAR(10) NOT NULL
)

CREATE TABLE tasks
(
	id INT PRIMARY KEY IDENTITY,
	competition INT NOT NULL FOREIGN KEY REFERENCES competitions(id),
	text VARCHAR(500) NOT NULL,
	answer_type INT NOT NULL FOREIGN KEY REFERENCES answer_types(id)
)

CREATE TABLE answer_options
(
	id INT PRIMARY KEY IDENTITY,
	task INT NOT NULL FOREIGN KEY REFERENCES tasks(id) ON DELETE CASCADE,
	text VARCHAR(1000) NOT NULL,
	mark INT NOT NULL DEFAULT 0
)

CREATE TABLE answers
(
	id INT PRIMARY KEY IDENTITY,
	participation INT NOT NULL FOREIGN KEY REFERENCES participation(id) ON DELETE CASCADE,
	answer_option INT NOT NULL FOREIGN KEY REFERENCES answer_options(id) ON DELETE CASCADE
)

CREATE TABLE results
(
	id INT PRIMARY KEY IDENTITY,
	participation INT NOT NULL FOREIGN KEY REFERENCES participation(id) ON DELETE CASCADE,
	place_in_top INT NOT NULL,
	mark INT NOT NULL
)

CREATE TABLE logs
(
	id INT PRIMARY KEY IDENTITY,
	account VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES accounts(email),
	type CHAR(6) NOT NULL CHECK (type IN ('CREATE', 'UPDATE', 'DELETE')),
	repr VARCHAR(1000) NOT NULL,
	creation_datetime DATETIME DEFAULT GETDATE()
)
